name: "Go Tests"

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Bench 
        run: go test -v -bench=./... -benchmem